gorillacarts/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from gorillacarts.lib.objects import Cart
from gorillacarts.lib.utils import getFormVariable, getIntegerFormVariable, getFloatFormVariable
from gorillacarts.lib.db import *

gorillacarts = Blueprint(
    'gorillacarts',
    __name__,
    template_folder='templates'
)

@gorillacarts.route('/', methods=['GET'])
def index():
    return render_template('gorillacarts/index.html' )

# ------------------------------------------------------------------------------------
# Customer routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/customers", methods=["GET"])
def customers():
    if request.method == "GET":
        customer_list=Cart.getAllCustomers()
        return render_template('gorillacarts/customers/index.html',customers=customer_list)

@gorillacarts.route('/customers/create', methods=['GET'])
def customers_create():
    if request.method == "GET":
        return render_template('gorillacarts/customers/create.html')
    
@gorillacarts.route("/customers/<id>/update", methods=['GET'])
def customers_update(id):
    if request.method == "GET":
        customer=getCustomerById(id)
        return render_template('gorillacarts/customers/update.html',customer=customer )

@gorillacarts.route('/api/customers/create', methods=['POST'])
def api_customers_create():
    name = request.form.get("name", 0)
    zip = request.form.get("ZIP", 0)
    telephone = request.form.get("telephone", 0)
    email = request.form.get("email", 0)
    category = request.form.get("category", 0)

    saveCustomerDB(name, zip, telephone, email, category)

    return redirect(url_for('gorillacarts.customers'))

@gorillacarts.route("/api/customers/<id>/update", methods=["POST"])
def api_customers_update(id):
    zip = getFormVariable(request,"ZIP")
    telephone = getFormVariable(request,"Telephone")
    email = getFormVariable(request,"Email")
    category = getFormVariable(request,"Category")

    updateCustomerDB(id, zip, telephone, email, category)
    
    return redirect(url_for('gorillacarts.customers'))

@gorillacarts.route("/api/customers/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_customers_delete(id):
    genDelete_DB("Customers","CustomerID",id)
    
    return redirect(url_for('gorillacarts.customers'))

# ------------------------------------------------------------------------------------
# Product routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/products", methods=["GET"]) # Decorator
def products():
    if request.method == "GET":
        product_list=Cart.getAllProducts()
        return render_template('gorillacarts/products/index.html',products=product_list)
    
@gorillacarts.route("/products/<id>", methods=['GET'])
def products_bom(id):
    if request.method == "GET":
        bom=getBOMByProductId(id)
        return render_template('gorillacarts/products/bom.html',bom=bom)
    
# ------------------------------------------------------------------------------------
# Material routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/materials", methods=["GET"]) # Decorator
def materials():
    if request.method == "GET":
        material_list=Cart.getAllMaterials()
        return render_template('gorillacarts/materials/index.html',materials=material_list)

@gorillacarts.route('/materials/create', methods=['GET'])
def materials_create():
    if request.method == "GET":
        supplier_list=Cart.getAllSuppliers()
        return render_template('gorillacarts/materials/create.html',suppliers=supplier_list)
    
@gorillacarts.route("/materials/<id>/update", methods=['GET'])
def materials_update(id):
    if request.method == "GET":
        material=getMaterialById(id)
        return render_template('gorillacarts/materials/update.html',material=material )
    
@gorillacarts.route('/api/materials/create', methods=['POST'])
def api_materials_create():
    if request.method == "POST":
        SWPartNo = request.form.get("SWPartNo", 0)
        SupplierPartNo = request.form.get("SupplierPartNo", 0)
        SupplierID = request.form.get("SupplierID", 0)
        ProductName = request.form.get("ProductName", 0)
        Price = request.form.get("Price", 0)
        QuantityAvailable = request.form.get("QuantityAvailable", 0)

        saveMaterialDB(SWPartNo,SupplierPartNo,SupplierID,ProductName,Price,QuantityAvailable)

        return redirect(url_for('gorillacarts.materials'))
    
@gorillacarts.route("/api/materials/<id>/update", methods=["POST"])
def api_materials_update(id):
    SupplierPartNo = getFormVariable(request,"SupplierPartNo")
    SupplierID = getIntegerFormVariable(request,"SupplierID")
    ProductName = getFormVariable(request,"ProductName")
    Price = getFormVariable(request,"Price")
    QuantityAvailable = getFloatFormVariable(request,"QuantityAvailable")

    updateMaterialDB(SupplierPartNo,SupplierID,ProductName,Price,QuantityAvailable,id)
    
    return redirect(url_for('gorillacarts.materials'))

@gorillacarts.route("/api/materials/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_materials_delete(id):
    genDelete_DB("Materials","SWPartNo",id)
    
    return redirect(url_for('gorillacarts.materials'))

# ------------------------------------------------------------------------------------
# Supplier routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/suppliers", methods=["GET"]) # Decorator
def suppliers():
    if request.method == "GET":
        supplier_list=Cart.getAllSuppliers()
        return render_template('gorillacarts/suppliers/index.html',suppliers=supplier_list)

@gorillacarts.route('/suppliers/create', methods=['GET'])
def suppliers_create():
    if request.method == "GET":
        return render_template('gorillacarts/suppliers/create.html')
    
@gorillacarts.route("/suppliers/<id>/update", methods=['GET'])
def suppliers_update(id):
    if request.method == "GET":
        supplier=getSupplierById(id)
        return render_template('gorillacarts/suppliers/update.html',supplier=supplier )
    
@gorillacarts.route('/api/suppliers/create', methods=['POST'])
def api_suppliers_create():
    if request.method == "POST":
        name = request.form.get("name", 0)
        zip = request.form.get("ZIP", 0)
        telephone = request.form.get("telephone", 0)
        email = request.form.get("email", 0)

        saveSupplierDB(name, zip, telephone, email)

        return redirect(url_for('gorillacarts.suppliers'))
    
@gorillacarts.route("/api/suppliers/<id>/update", methods=["POST"])
def api_suppliers_update(id):
    zip = getFormVariable(request,"ZIP")
    telephone = getFormVariable(request,"Telephone")
    email = getFormVariable(request,"Email")

    updateSupplierDB(zip, telephone, email, id)
    
    return redirect(url_for('gorillacarts.suppliers'))

@gorillacarts.route("/api/suppliers/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_suppliers_delete(id):
    genDelete_DB("Suppliers","SupplierID",id)
    
    return redirect(url_for('gorillacarts.suppliers'))

# ------------------------------------------------------------------------------------
# Order routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/orders", methods=["GET"]) # Decorator
def orders():
    if request.method == "GET":
        order_list=Cart.getAllOrders()
        return render_template('gorillacarts/orders/index.html',orders=order_list)

@gorillacarts.route("/orders/<id>", methods=['GET'])
def orders_details(id):
    if request.method == "GET":
        order=getOrderById(id)
        order_details=getOrderDetailsById(id)
        return render_template('gorillacarts/orders/details.html',order=order,order_details=order_details)
    
@gorillacarts.route('/orders/create', methods=['GET'])
def orders_create():
    if request.method == "GET":
        staff_list=Cart.getAllStaff()
        customer_list=Cart.getAllCustomers()
        product_list=Cart.getAllProducts()
        return render_template('gorillacarts/orders/create.html',staff=staff_list,customers=customer_list,products=product_list)

@gorillacarts.route("/api/orders/create", methods=["GET","POST"]) # Decorator - Now
def placeorder():
    if request.method == "POST": # When you fill out the form and click SUBMIT
        # C1) Run a CLASS method called getAllMovies().  Instaniation is not needed.
        staff_list=Cart.getAllStaff()
        customer_list=Cart.getAllCustomers()
        product_list=Cart.getAllProducts()
        order_list=Cart.getAllOrders()
        material_list=Cart.getAllMaterials()
        bom_list=Cart.getAllBOMs()

        # Get the value from the form object (it is a drop down menu)
        EmployeeID = request.form.get("EmployeeID", 0)
        CustomerID = request.form.get("CustomerID", 0)
        ProductID1 = request.form.get("ProductID1", 0)
        Quantity1 = request.form.get("quantity1", 0)
        ProductID2 = request.form.get("ProductID2", 0)
        Quantity2 = request.form.get("quantity2", 0)
        ProductID3 = request.form.get("ProductID3", 0)
        Quantity3 = request.form.get("quantity3", 0)
        ProductID4 = request.form.get("ProductID4", 0)
        Quantity4 = request.form.get("quantity4", 0)
        ProductID5 = request.form.get("ProductID5", 0)
        Quantity5 = request.form.get("quantity5", 0)

        #-------------------------------------
        # 1. VERIFY IF THE PLACED ORDER DOESN'T HAVE A PRODUCT WHOSE QUANTITY IS MORE THAN 10
        #-------------------------------------
        order = {}
        if ProductID1 != "" and Quantity1 != "":
            if ProductID1 not in order.keys():
                order[ProductID1] = int(Quantity1)
            else:

gorillacarts/templates/gorillacarts/orders/create.html
<!-- CREATE CHILD TEMPLATE FOR "ADD" PAGE (aka Insert Record Page) -->
<!-- Inherit the Parent page first -->
{% extends "gorillacarts/layout.html" %}

<!-- Replace the "placeholder" called head in the parent template with the following -->
{% block head %}
    <title>Place Order</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a class="active" href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}


<!-- Replace the "placeholder" called body in the parent template with the following -->
{% block body %}

    <form action="/gorillacarts/api/orders/create" method="post">
        <!-- START Specific to Movie Add -->
        <H2><u>Place Order</u></H2>
        <!-- Name this TEXTBOX "movname"-->
        <TABLE style="border-collapse: collapse; width:50%">
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Employee ID</TD>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;"><select style="width:200px" name="EmployeeID" id="EmployeeID">
                    {% for employee in staff %}
                        <option value="{{employee.EmployeeID}}">{{employee.EmployeeID}} | {{employee.Name}}</option>
                    {% endfor %}
                </select></TD>
            </TR>
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Customer ID</TD>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;"><select style="width:200px" name="CustomerID" id="CustomerID">
                    {% for customer in customers %}
                        <option value="{{customer.CustomerID}}">{{customer.CustomerID}} | {{customer.Name}}</option>
                    {% endfor %}
                </select></TD>
            </TR>
        </TABLE>
<br>
<br>
        <TABLE style="border-collapse: collapse; width:50%">
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Product</TD>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Quantity</TD>
            </TR>
            <TR>
                <td style="padding: 5px; border: solid 1px #777; width:90px;">1. <select name="ProductID1" id="ProductID1">
                    <option value=""></option>
                    {% for product in products %}
                        <option value="{{product.ProductID}}">{{product.ProductID}} | {{product.ProductName}} ({{product.Color}})</option>
                    {% endfor %}
                </select></td>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;">
                    <select name="quantity1" id="quantity1">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </TD>
            </TR>
            <TR>
                <td style="padding: 5px; border: solid 1px #777; width:90px;">2. <select name="ProductID2" id="ProductID2">
                    <option value=""></option>
                    {% for product in products %}
                        <option value="{{product.ProductID}}">{{product.ProductID}} | {{product.ProductName}} ({{product.Color}})</option>
                    {% endfor %}
                </select></td>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;">
                    <select name="quantity2" id="quantity2">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </TD>
            </TR>
            <TR>
                <td style="padding: 5px; border: solid 1px #777; width:90px;">3. <select name="ProductID3" id="ProductID3">
                    <option value=""></option>
                    {% for product in products %}
                        <option value="{{product.ProductID}}">{{product.ProductID}} | {{product.ProductName}} ({{product.Color}})</option>
                    {% endfor %}
                </select></td>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;">
                    <select name="quantity3" id="quantity3">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </TD>
            </TR>
            <TR>
                <td style="padding: 5px; border: solid 1px #777; width:90px;">4. <select name="ProductID4" id="ProductID4">
                    <option value=""></option>
                    {% for product in products %}
                        <option value="{{product.ProductID}}">{{product.ProductID}} | {{product.ProductName}} ({{product.Color}})</option>
                    {% endfor %}
                </select></td>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;">
                    <select name="quantity4" id="quantity4">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </TD>
            </TR>
            <TR>
                <td style="padding: 5px; border: solid 1px #777; width:90px;">5. <select name="ProductID5" id="ProductID5">
                    <option value=""></option>
                    {% for product in products %}
                        <option value="{{product.ProductID}}">{{product.ProductID}} | {{product.ProductName}} ({{product.Color}})</option>
                    {% endfor %}
                </select></td>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;">
                    <select name="quantity5" id="quantity5">
                        <option value=""></option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </TD>
            </TR>


        </TABLE>





        <!-- Add a Submit button-->
        <br>
        <input type="submit" style="background-color: #008CBA; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;">
        <br>
        <br>
            {{errormessage}}
        <br>
        <br>
        {% if errorpart2|length > 0 %}
            <table style="border-collapse: collapse; width:30%">
                <tr style="background-color: #ff3333;">
                    <th style="padding: 5px; border: solid 1px #777; color:white;">Part Number</th>
                    <th style="padding: 5px; border: solid 1px #777; color:white;">Amount Missing</th>
                </tr>
                {% for i in errorpart2 %}
                    <tr>
                        <td style="padding: 5px; border: solid 1px #777; width:90px;">{{i}}</td>
                        <td style="padding: 5px; border: solid 1px #777; width:90px;">{{errorpart2[i]}}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
        <br>
        {{errormessage2}}
        <br>
        <br>
        {% if errorpart3|length > 0 %}
            <table style="border-collapse: collapse; width:30%">
                <tr style="background-color: #ff3333;">
                    <th style="padding: 5px; border: solid 1px #777; color:white;">Product ID</th>
                    <th style="padding: 5px; border: solid 1px #777; color:white;">Purchasable Amount</th>
                </tr>
                {% for i in errorpart3 %}
                    <tr>
                        <td style="padding: 5px; border: solid 1px #777; width:90px;">{{i}}</td>
                        <td style="padding: 5px; border: solid 1px #777; width:90px;">{{errorpart3[i]}}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
        <br>
        <!-- END Specific to Movie Add -->
    </form>

 {% endblock %}

gorillacarts/templates/gorillacarts/orders/details.html
{% extends "gorillacarts/layout.html" %}

{% block head %}
    <title>View Invoice</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a class="active" href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}

{% block body %}

    <table width="100%">
        <tr>
            <td colspan="3">
                <h1>Order Invoice</h1>
                <H2><u>Order ID: {{order['OrderID']}}</u></H2>
                <p>Order Date: {{order['Date']}}</p>
            </td>
        </tr>
    </table>

    {% for item in order_details %}
    <TABLE style="border-collapse: collapse; width:50%">
        <TR>
            <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE; width:50%;">Product Name</TD>
            <TD style="padding: 5px; border: solid 1px #777;">{{item.ProductName}}</TD>
        </TR>
        <TR>
            <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Product ID</TD>
            <TD style="padding: 5px; border: solid 1px #777;">{{item.ProductID}}</TD>
        </TR>
        <TR>
            <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Quantity</TD>
            <TD style="padding: 5px; border: solid 1px #777;">{{item.Qty}}</TD>
         </TR>
         <TR>
            <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Amount Receivable</TD>
            <TD style="padding: 5px; border: solid 1px #777;">${{"{:.2f}".format(item.AmtPayable)}}</TD>
         </TR>
    </TABLE>
    {% endfor %}
    
    <br>

    <br>


{% endblock %}

gorillacarts/templates/gorillacarts/orders/index.html
{% extends "gorillacarts/layout.html" %}

<!-- Replace the "placeholder" called head in the parent template with the following -->
{% block head %}
    <title>Orders</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a class="active" href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}

<!-- Replace the "placeholder" called body in the parent template with the following -->
{% block body %}

<!-- NOTE***** NO ACTION OR METHOD - WE ARE JUST USING THE LINKS BELOW-->
<form>
     <H2><u>Orders</u></H2>
     <TABLE style="border-collapse: collapse;">
         <TR style="background-color: #D6EEEE;">
            <TH style="padding: 5px; border: solid 1px #777; width:250px;">Order ID (Click for Receipt)</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Customer ID</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Employee ID</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Total</TD>
        </TH>
         {% for order in orders %}
             <TR>
                  <TD style="padding: 5px; border: solid 1px #777;"><a href="{{ url_for('gorillacarts.orders_details', id=order.OrderID) }}">{{order.OrderID}}</a></TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{order.CustomerID}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{order.EmpID}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">${{"{:.2f}".format(order.Total)}}</TD>
             </TR>
         {% endfor %}
     </TABLE>
     <br>
     <a href="/gorillacarts/orders/create" style="background-color: #008CBA; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;">Create Order</a>

</form>




{% endblock %}