gorillacarts/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from gorillacarts.lib.objects import Cart
from gorillacarts.lib.utils import getFormVariable, getIntegerFormVariable, getFloatFormVariable
from gorillacarts.lib.db import *

gorillacarts = Blueprint(
    'gorillacarts',
    __name__,
    template_folder='templates'
)

@gorillacarts.route('/', methods=['GET'])
def index():
    return render_template('gorillacarts/index.html' )

# ------------------------------------------------------------------------------------
# Customer routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/customers", methods=["GET"])
def customers():
    if request.method == "GET":
        customer_list=Cart.getAllCustomers()
        return render_template('gorillacarts/customers/index.html',customers=customer_list)

@gorillacarts.route('/customers/create', methods=['GET'])
def customers_create():
    if request.method == "GET":
        return render_template('gorillacarts/customers/create.html')
    
@gorillacarts.route("/customers/<id>/update", methods=['GET'])
def customers_update(id):
    if request.method == "GET":
        customer=getCustomerById(id)
        return render_template('gorillacarts/customers/update.html',customer=customer )

@gorillacarts.route('/api/customers/create', methods=['POST'])
def api_customers_create():
    name = request.form.get("name", 0)
    zip = request.form.get("ZIP", 0)
    telephone = request.form.get("telephone", 0)
    email = request.form.get("email", 0)
    category = request.form.get("category", 0)

    saveCustomerDB(name, zip, telephone, email, category)

    return redirect(url_for('gorillacarts.customers'))

@gorillacarts.route("/api/customers/<id>/update", methods=["POST"])
def api_customers_update(id):
    zip = getFormVariable(request,"ZIP")
    telephone = getFormVariable(request,"Telephone")
    email = getFormVariable(request,"Email")
    category = getFormVariable(request,"Category")

    updateCustomerDB(id, zip, telephone, email, category)
    
    return redirect(url_for('gorillacarts.customers'))

@gorillacarts.route("/api/customers/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_customers_delete(id):
    genDelete_DB("Customers","CustomerID",id)
    
    return redirect(url_for('gorillacarts.customers'))

# ------------------------------------------------------------------------------------
# Product routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/products", methods=["GET"]) # Decorator
def products():
    if request.method == "GET":
        product_list=Cart.getAllProducts()
        return render_template('gorillacarts/products/index.html',products=product_list)
    
@gorillacarts.route("/products/<id>", methods=['GET'])
def products_bom(id):
    if request.method == "GET":
        bom=getBOMByProductId(id)
        return render_template('gorillacarts/products/bom.html',bom=bom)
    
# ------------------------------------------------------------------------------------
# Material routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/materials", methods=["GET"]) # Decorator
def materials():
    if request.method == "GET":
        material_list=Cart.getAllMaterials()
        return render_template('gorillacarts/materials/index.html',materials=material_list)

@gorillacarts.route('/materials/create', methods=['GET'])
def materials_create():
    if request.method == "GET":
        supplier_list=Cart.getAllSuppliers()
        return render_template('gorillacarts/materials/create.html',suppliers=supplier_list)
    
@gorillacarts.route("/materials/<id>/update", methods=['GET'])
def materials_update(id):
    if request.method == "GET":
        material=getMaterialById(id)
        return render_template('gorillacarts/materials/update.html',material=material )
    
@gorillacarts.route('/api/materials/create', methods=['POST'])
def api_materials_create():
    if request.method == "POST":
        SWPartNo = request.form.get("SWPartNo", 0)
        SupplierPartNo = request.form.get("SupplierPartNo", 0)
        SupplierID = request.form.get("SupplierID", 0)
        ProductName = request.form.get("ProductName", 0)
        Price = request.form.get("Price", 0)
        QuantityAvailable = request.form.get("QuantityAvailable", 0)

        saveMaterialDB(SWPartNo,SupplierPartNo,SupplierID,ProductName,Price,QuantityAvailable)

        return redirect(url_for('gorillacarts.materials'))
    
@gorillacarts.route("/api/materials/<id>/update", methods=["POST"])
def api_materials_update(id):
    SupplierPartNo = getFormVariable(request,"SupplierPartNo")
    SupplierID = getIntegerFormVariable(request,"SupplierID")
    ProductName = getFormVariable(request,"ProductName")
    Price = getFormVariable(request,"Price")
    QuantityAvailable = getFloatFormVariable(request,"QuantityAvailable")

    updateMaterialDB(SupplierPartNo,SupplierID,ProductName,Price,QuantityAvailable,id)
    
    return redirect(url_for('gorillacarts.materials'))

@gorillacarts.route("/api/materials/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_materials_delete(id):
    genDelete_DB("Materials","SWPartNo",id)
    
    return redirect(url_for('gorillacarts.materials'))

# ------------------------------------------------------------------------------------
# Supplier routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/suppliers", methods=["GET"]) # Decorator
def suppliers():
    if request.method == "GET":
        supplier_list=Cart.getAllSuppliers()
        return render_template('gorillacarts/suppliers/index.html',suppliers=supplier_list)

@gorillacarts.route('/suppliers/create', methods=['GET'])
def suppliers_create():
    if request.method == "GET":
        return render_template('gorillacarts/suppliers/create.html')
    
@gorillacarts.route("/suppliers/<id>/update", methods=['GET'])
def suppliers_update(id):
    if request.method == "GET":
        supplier=getSupplierById(id)
        return render_template('gorillacarts/suppliers/update.html',supplier=supplier )
    
@gorillacarts.route('/api/suppliers/create', methods=['POST'])
def api_suppliers_create():
    if request.method == "POST":
        name = request.form.get("name", 0)
        zip = request.form.get("ZIP", 0)
        telephone = request.form.get("telephone", 0)
        email = request.form.get("email", 0)

        saveSupplierDB(name, zip, telephone, email)

        return redirect(url_for('gorillacarts.suppliers'))
    
@gorillacarts.route("/api/suppliers/<id>/update", methods=["POST"])
def api_suppliers_update(id):
    zip = getFormVariable(request,"ZIP")
    telephone = getFormVariable(request,"Telephone")
    email = getFormVariable(request,"Email")

    updateSupplierDB(zip, telephone, email, id)
    
    return redirect(url_for('gorillacarts.suppliers'))

@gorillacarts.route("/api/suppliers/<id>/delete", methods=['POST', 'DELETE', 'GET'])
def api_suppliers_delete(id):
    genDelete_DB("Suppliers","SupplierID",id)
    
    return redirect(url_for('gorillacarts.suppliers'))

# ------------------------------------------------------------------------------------
# Order routes
# ------------------------------------------------------------------------------------

@gorillacarts.route("/orders", methods=["GET"]) # Decorator
def orders():
    if request.method == "GET":
        order_list=Cart.getAllOrders()
        return render_template('gorillacarts/orders/index.html',orders=order_list)

@gorillacarts.route("/orders/<id>", methods=['GET'])
def orders_details(id):
    if request.method == "GET":
        order=getOrderById(id)
        order_details=getOrderDetailsById(id)
        return render_template('gorillacarts/orders/details.html',order=order,order_details=order_details)
    
@gorillacarts.route('/orders/create', methods=['GET'])
def orders_create():
    if request.method == "GET":
        staff_list=Cart.getAllStaff()
        customer_list=Cart.getAllCustomers()
        product_list=Cart.getAllProducts()
        return render_template('gorillacarts/orders/create.html',staff=staff_list,customers=customer_list,products=product_list)

@gorillacarts.route("/api/orders/create", methods=["GET","POST"]) # Decorator - Now
def placeorder():
    if request.method == "POST": # When you fill out the form and click SUBMIT
        # C1) Run a CLASS method called getAllMovies().  Instaniation is not needed.
        staff_list=Cart.getAllStaff()
        customer_list=Cart.getAllCustomers()
        product_list=Cart.getAllProducts()
        order_list=Cart.getAllOrders()
        material_list=Cart.getAllMaterials()
        bom_list=Cart.getAllBOMs()

        # Get the value from the form object (it is a drop down menu)
        EmployeeID = request.form.get("EmployeeID", 0)
        CustomerID = request.form.get("CustomerID", 0)
        ProductID1 = request.form.get("ProductID1", 0)
        Quantity1 = request.form.get("quantity1", 0)
        ProductID2 = request.form.get("ProductID2", 0)
        Quantity2 = request.form.get("quantity2", 0)
        ProductID3 = request.form.get("ProductID3", 0)
        Quantity3 = request.form.get("quantity3", 0)
        ProductID4 = request.form.get("ProductID4", 0)
        Quantity4 = request.form.get("quantity4", 0)
        ProductID5 = request.form.get("ProductID5", 0)
        Quantity5 = request.form.get("quantity5", 0)

        #-------------------------------------
        # 1. VERIFY IF THE PLACED ORDER DOESN'T HAVE A PRODUCT WHOSE QUANTITY IS MORE THAN 10
        #-------------------------------------
        order = {}
        if ProductID1 != "" and Quantity1 != "":
            if ProductID1 not in order.keys():
                order[ProductID1] = int(Quantity1)
            else:

gorillacarts/templates/gorillacarts/materials/create.html
{% extends "gorillacarts/layout.html" %}

<!-- Replace the "placeholder" called head in the parent template with the following -->
{% block head %}
    <title>Add Material</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a class="active" href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}


<!-- Replace the "placeholder" called body in the parent template with the following -->
{% block body %}

    <form action="/gorillacarts/api/materials/create" method="post">
        <!-- START Specific to Movie Add -->
        <H2><u>Add Material</u></H2>
        <!-- Name this TEXTBOX "movname"-->

        <TABLE style="border-collapse: collapse; width:50%">
            <TR>
               <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">SW Part No.</TD>
                <TD style="padding: 5px; border: solid 1px #777; width:90px;"><input autocomplete="off" autofocus name="SWPartNo" placeholder="SW Part No" type="text" required></TD>
            </TR>
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Supplier Part No.</TD>
                 <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="SupplierPartNo" placeholder="Supplier Part No" type="text" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Supplier ID</TD>
                <td style="padding: 5px; border: solid 1px #777;"><select name="SupplierID" id="SupplierID">
                    {% for supplier in suppliers %}
                    <option value="{{supplier.SupplierID}}">{{supplier.SupplierID}} | {{supplier.Name}}</option>
                    {% endfor %}
                </select></td>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Product Name</TD>
                 <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="ProductName" placeholder="Product Name" type="text" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Price</TD>
                 <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="Price" placeholder="Price" type="Double" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Quantity Available</TD>
                 <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="QuantityAvailable" placeholder="Quantity Available" type="integer" required></TD>
             </TR>
        </TABLE>
        <!-- Add a Submit button-->
        <br>
        <input type="submit" style="background-color: #008CBA; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;">
        <br>
        <br>
        <!-- END Specific to Movie Add -->
    </form>

 {% endblock %}

gorillacarts/templates/gorillacarts/materials/index.html
{% extends "gorillacarts/layout.html" %}

<!-- Replace the "placeholder" called head in the parent template with the following -->
{% block head %}
    <title>Materials</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a class="active" href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}

<!-- Replace the "placeholder" called body in the parent template with the following -->
{% block body %}

<!-- NOTE***** NO ACTION OR METHOD - WE ARE JUST USING THE LINKS BELOW-->
<form>
     <H2><u>Materials</u></H2>
     <TABLE style="border-collapse: collapse;">
         <TR style="background-color: #D6EEEE;">
            <TH style="padding: 5px; border: solid 1px #777;">SW Part No.</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Supplier Part No.</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Supplier ID</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Product Name</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Price</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Quantity Available</TD>
            <TH style="padding: 5px; border: solid 1px #777;">Delete</TD>
        </TH>
        <!-- EXAMPLES OF THE JINJA LANGUAGE FOR LOOPS-->
         {% for material in materials %}
             <TR>
                  <TD style="padding: 5px; border: solid 1px #777;"><a href="{{ url_for('gorillacarts.materials_update', id=material.SWPartNo) }}">{{material.SWPartNo}}</a></TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{material.SupplierPartNo}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{material.SupplierID}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{material.ProductName}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">${{"{:.2f}".format(material.Price)}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;">{{"{:.2f}".format(material.QuantityAvailable)}}</TD>
                  <TD style="padding: 5px; border: solid 1px #777;"><a href="{{ url_for('gorillacarts.api_materials_delete', id=material.SWPartNo) }}">Delete</a></TD>
             </TR>
         {% endfor %}
     </TABLE>
    <br>
    <a href="/gorillacarts/materials/create" style="background-color: #008CBA; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;">Create Material</a>

</form>

{% endblock %}

gorillacarts/templates/gorillacarts/materials/update.html
{% extends "gorillacarts/layout.html" %}

<!-- Replace the "placeholder" called head in the parent template with the following -->
{% block head %}
    <title>Edit Material</title>
    <div class="topnav">
        <a href="{{ url_for('gorillacarts.index') }}">Home</a>
        <a href="{{ url_for('gorillacarts.customers') }}">Customers</a>
        <a href="{{ url_for('gorillacarts.products') }}">Products</a>
        <a class="active" href="{{ url_for('gorillacarts.materials') }}">Materials</a>
        <a href="{{ url_for('gorillacarts.suppliers') }}">Suppliers</a>
        <a href="{{ url_for('gorillacarts.orders') }}">Orders</a>
    </div>
{% endblock %}

{% block body %}

<form action="{{ url_for('gorillacarts.api_materials_update', id=material.SWPartNo) }}" method="post">
    <table width="100%">
        <tr>
            <td colspan="3">
                <h1>Update Material: {{material.SWPartNo}}</h1>
            </td>
        </tr>
    </table>
    <table>

    </table>
            <TABLE style="border-collapse: collapse; width:50%">
            <tr>
                <td style="text-align: left">
                    <input
                    type="hidden"
                    autocomplete="off"
                    autofocus
                    name="SWPartNo"
                    placeholder="SWPartNo"
                    type="text"
                    value="{{material.SWPartNo}}"
                    required>
                </td>
            </tr>
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Supplier Part No</TD>
                <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="SupplierPartNo" placeholder="SupplierPartNo" value="{{material.SupplierPartNo}}" type="text" required></TD>
            </TR>
            <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Supplier ID</TD>
                <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="SupplierID" placeholder="SupplierID" value="{{material.SupplierID}}" type="integer" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Product Name</TD>
                <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="ProductName" placeholder="ProductName" value="{{material.ProductName}}" type="text" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Price</TD>
                <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="Price" placeholder="Price" value="{{material.Price}}" type="double" required></TD>
             </TR>
             <TR>
                <TH style="padding: 5px; border: solid 1px #777; background-color: #D6EEEE;">Quantity Available</TD>
                <TD style="padding: 5px; border: solid 1px #777;"><input autocomplete="off" autofocus name="QuantityAvailable" placeholder="Quantity Available" value="{{material.QuantityAvailable}}" type="integer" required></TD>
             </TR>
        </TABLE>
    <br>
    <input type="submit" style="background-color: #008CBA; border: none; color: white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px;">


    <!-- END Specific to Movie Add -->


</form>

{% endblock %}